# Generated by Django 4.1.7 on 2023-03-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeT',
            new_name='About',
        ),
    ]
