# Generated by Django 4.1.7 on 2023-03-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0002_rename_homet_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
